apiVersion: v1
kind: Service
metadata:
  name: hadoop-datanode-service
  labels:
    microservice: datanode
  name: datanode
spec:
  type: LoadBalancer
  ports:
    - port: 9864
      targetPort: 9864
  selector:
    microservice: datanode