apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-worker-config
data:
  SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: 'no'
  SPARK_MASTER_URL: 'spark://35.237.30.163:7077'  # update this to master's external ip 
  SPARK_MODE: 'worker'
  SPARK_RPC_AUTHENTICATION_ENABLED: 'no'
  SPARK_RPC_ENCRYPTION_ENABLED: 'no'
  SPARK_SSL_ENABLED: 'no'
  SPARK_WORKER_CORES: '1'
  SPARK_WORKER_MEMORY: '1G'