---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-service
  labels:
    microservice: spark-worker
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
  selector:
    microservice: spark-worker