---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-worker
  labels:
    microservice: spark-worker
spec:
  serviceName: spark-worker
  replicas: 1
  selector:
    matchLabels:
      microservice: spark-worker
  template:
    metadata:
      labels:
        microservice: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: bitnami/spark:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: spark-worker-config
      restartPolicy: Always