apiVersion: apps/v1
kind: Deployment
metadata:
  name: namenode-deployment
  labels:
    microservice: namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      microservice: namenode
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        microservice: namenode
    spec:
      containers:
        - name: namenode
          env:
            - name: CLUSTER_NAME
              value: test
          envFrom:
            - configMapRef:
                name: hadoop-env
          image: {{ .Values.imagePath }}
          ports:
            - containerPort: 9870
            - containerPort: 9000
      #     volumeMounts:
      #       - mountPath: /hadoop/dfs/name
      #         name: hadoop-namenode
      # restartPolicy: Always
      # resources: {}
      # volumes:
      #   - name: hadoop-namenode
      #     persistentVolumeClaim:
      #       claimName: hadoop-namenode
