apiVersion: v1
kind: Service
metadata:
  name: namenode-service
  labels:
    microservice: namenode
  name: namenode
spec:
  type: LoadBalancer
  ports:
    - name: "9870"
      port: 80
      targetPort: 9870
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    microservice: namenode
