---
apiVersion: v1
kind: Service
metadata:
  name: spark-service
  labels:
    microservice: spark
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    microservice: spark