---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deployment
  labels:
    microservice: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      microservice: sonarqube
  template:
    metadata:
      labels:
        microservice: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: {{ .Values.imagePath }}
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: sonarqube-config
          resources:
            requests:
              cpu: "200m"