---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  labels:
    microservice: sonarqube
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9000
  selector:
    microservice: sonarqube