apiVersion: v1
kind: Service
metadata:
  name: datanode-service
  labels:
    microservice: datanode
  name: datanode
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9864
  selector:
    microservice: datanode