apiVersion: v1
kind: Service
metadata:
  name: namenode
  labels:
    microservice: namenode
spec:
  clusterIP: "None" 
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    microservice: namenode
---
apiVersion: v1
kind: Service
metadata:
  name: namenode-ui
  labels:
    microservice: namenode-ui
spec:
  type: LoadBalancer
  ports:
    - name: "9870"
      port: 9870
      targetPort: 9870
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    microservice: namenode
