apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: namenode
  labels:
    microservice: namenode
spec:
  serviceName: namenode
  replicas: 1
  selector:
    matchLabels:
      microservice: namenode
  template:
    metadata:
      labels:
        microservice: namenode
    spec:
      containers:
        - name: namenode
          env:
            - name: CLUSTER_NAME
              value: big-data
          envFrom:
            - configMapRef:
                name: hadoop-env
          image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
          ports:
            - containerPort: 9870
            - containerPort: 9000
      #     volumeMounts:
      #       - name: dfs 
      #         mountPath: /hadoop/dfs/name
      restartPolicy: Always
      # volumes:
      #   - name: dfs
      #     persistentVolumeClaim:
      #       claimName: dfs-hadoop-namenode