apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
  labels:
    microservice: jupyter
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8888
  selector:
    microservice: jupyter