apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-master-config
data:
  SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: 'no'
  SPARK_MODE: 'master'
  SPARK_RPC_AUTHENTICATION_ENABLED: 'no'
  SPARK_RPC_ENCRYPTION_ENABLED: 'no'
  SPARK_SSL_ENABLED: 'no'
