---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-deployment
  labels:
    microservice: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      microservice: spark
  template:
    metadata:
      labels:
        microservice: spark
    spec:
      containers:
        - name: spark-master
          image: bitnami/spark:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spark-master-config
        # - name: spark-worker
        #   image: bitnami/spark:latest
        #   ports:
        #     - containerPort: 8081
        #   envFrom:
        #     - configMapRef:
        #         name: spark-worker-config
      restartPolicy: Always