---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-deployment
  labels:
    microservice: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      microservice: spark
  template:
    metadata:
      labels:
        microservice: spark
    spec:
      containers:
        - name: spark-master
          image: bitnami/spark:latest
          ports:
            - containerPort: 8080
            - containerPort: 7077
          envFrom:
            - configMapRef:
                name: spark-master-config
      restartPolicy: Always