---
apiVersion: v1
kind: Service
metadata:
  name: spark-service
  labels:
    microservice: spark
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    microservice: spark