---
apiVersion: v1
kind: Service
metadata:
  name: spark-service
  labels:
    microservice: spark
spec:
  type: LoadBalancer
  ports:
    - name: masterui
      port: 80
      targetPort: 8080
    - name: jobsubmit
      port: 7077
      targetPort: 7077
  selector:
    microservice: spark