---
apiVersion: v1
kind: Service
metadata:
  name: ui-app-service
  labels:
    microservice: ui-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4000
  selector:
    microservice: ui-app