apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ui-app
  labels:
    microservice: ui-app
spec:
  serviceName: ui-app
  replicas: 1
  selector:
    matchLabels:
      microservice: ui-app
  template:
    metadata:
      labels:
        microservice: ui-app
    spec:
      containers:
        - name: ui-app
          image: xxpan/big-data-app:latest
          ports:
            - containerPort: 4000