---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-deployment
  labels:
    microservice: spark-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      microservice: spark-worker
  template:
    metadata:
      labels:
        microservice: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: {{ $imagePath }}
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: spark-worker-config
      restartPolicy: Alway